### Получаем инфу о БД
#curl -v http://localhost:8080/db/{db_name}
### Проставляем признак активности для БД
#curl -X PUT http://localhost:8080/db/sched/{db_name}
### Убираем признак активности для БД
#curl -X DELETE http://localhost:8080/db/sched/{db_name}

--------------
### Получаем инфу о БД
#curl -v http://localhost:8080/db/{db_name}
### Получаем инфу о БД
#curl -v http://localhost:8080/db/{db_name}### Получаем инфу о БД
#curl -v http://localhost:8080/db/{db_name}

###
GET http://localhost:8080/db
###
GET http://localhost:8080/db/DB1
###
PUT http://localhost:8080/db/sched/DB1
